
language: csharp
solution: unity.sln
git:
  submodules: false
branches:
  only:
    - master
    - development
env:
  matrix:
    - MONO_VERSION="3.5.0"
before_install:
    - "npm install unity-solution -g"
    - "unitysolution ./UBS Standalone"
script:
    - "xbuild /p:Configuration=Debug unity.sln"
    - "unitysolution ./UBS iOS && xbuild /p:Configuration=Debug unity.sln"
    - "unitysolution ./UBS Android && xbuild /p:Configuration=Debug unity.sln"